---
abstract: 'Parse cpanfile'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-CPANfile
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
recommends:
  Pod::Usage: 0
requires:
  CPAN::Meta: 2.12091
  CPAN::Meta::Prereqs: 2.12091
  parent: 0
resources:
  bugtracker: https://github.com/miyagawa/cpanfile/issues
  homepage: https://github.com/miyagawa/cpanfile
  repository: https://github.com/miyagawa/cpanfile.git
version: 1.0904
x_contributors:
  - 'Atsushi Kato <ktat@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Masahiro Honma <hiratara@cpan.org>'
  - 'Michiel Beijen <michiel.beijen@gmail.com>'
  - 'grtodd <gtodd@iciti.ca>'
  - 'ikasam_a <masaki.nakagawa@gmail.com>'
